---

  ##install and configure apache and php5
- name: config php5
  include: php5.yml

  ##install and configure apache as reverse proxy
- name: config apache
  include: apache.yml
  when: reverse_proxy_type == "apache"

  ##download ocs and unarchive
- name: download ocs and unarchive
  unarchive:
    src: https://pkp.sfu.ca/ocs/download/ocs-2.3.6.tar.gz
    dest: /var/www/html
    remote_src: yes

 ##directories permissions
- name: grant directories permissions
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 0777
  with_items:
    - /var/www/html/ocs-2.3.6/public
    - /var/www/html/ocs-2.3.6/cache
    - /var/www/html/ocs-2.3.6/cache/t_compile
    - /var/www/html/ocs-2.3.6/cache/t_cache
    - /var/www/html/ocs-2.3.6/cache/t_config
    - /var/www/html/ocs-2.3.6/cache/_db

##file permissions
- name: grant file permissions
  file:
    path: "{{ item }}"
    state: file
    mode: 0666
  with_items:
    - /var/www/html/ocs-2.3.6/config.inc.php